# Generated by Django 3.2.7 on 2021-10-19 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('Full_Name', models.CharField(max_length=200)),
                ('industry_type', models.CharField(max_length=200)),
                ('presenter', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('paper', models.FileField(blank=True, null=True, upload_to='papers/', verbose_name='paper')),
                ('guests', models.IntegerField(default=0, null=True)),
                ('courses_subscribed', models.IntegerField(default=0)),
                ('receipt_photo', models.ImageField(default='None', null=True, upload_to='receipts/', verbose_name='Receipt Photo')),
                ('course_1_name', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('course_1_id', models.IntegerField(default=0, null=True)),
                ('course_1_link', models.CharField(default='None', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=450)),
                ('background_image', models.ImageField(upload_to='images/')),
                ('logo_image', models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_length', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='Workshop@mail.com', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('presenter', models.CharField(max_length=200)),
                ('image', models.ImageField(default='None/conisoft_logo_0SeqbbO.png', upload_to='images/')),
                ('presenter_image', models.ImageField(upload_to='images/')),
                ('attendants', models.IntegerField(default=0)),
                ('max_size', models.IntegerField(default=20)),
                ('zoom_link', models.CharField(blank=True, max_length=500)),
                ('approved', models.BooleanField(default=False)),
                ('atendee_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
