# Generated by Django 3.2.7 on 2021-10-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_length', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='course@mail.com', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('presenter', models.CharField(max_length=200)),
                ('image', models.ImageField(default='None/conisoft_logo_0SeqbbO.png', upload_to='images/')),
                ('presenter_image', models.ImageField(upload_to='images/')),
                ('attendants', models.IntegerField(default=0)),
                ('max_size', models.IntegerField(default=20)),
                ('zoom_link', models.CharField(blank=True, max_length=500)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
