# Generated by Django 3.2.5 on 2021-07-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('presenter', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('open_slots', models.IntegerField()),
                ('taken_slots', models.IntegerField(default=0)),
                ('zoom_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
