# Generated by Django 3.2.5 on 2021-07-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_worshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
