# Generated by Django 3.2.5 on 2021-07-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_bullet_carosel_course_edition_paperrequirement_topics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
