# Generated by Django 3.2.5 on 2021-07-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20210730_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
