# Generated by Django 3.2.5 on 2021-08-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_edition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='image',
            field=models.URLField(),
        ),
    ]
