# Generated by Django 3.2.5 on 2021-08-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_edition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
