# Generated by Django 3.2.5 on 2021-08-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20210801_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='about',
        ),
        migrations.AddField(
            model_name='paperrequirement',
            name='text1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paperrequirement',
            name='text2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paperrequirement',
            name='text3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paperrequirement',
            name='text4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paperrequirement',
            name='text5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='about1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='about2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='about3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='about4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='about5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Bullet',
        ),
    ]
