# Generated by Django 3.2.5 on 2021-08-06 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20210803_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paper',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='reciept',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
