# Generated by Django 3.2.6 on 2021-08-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_user_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='reciept',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
