# Generated by Django 3.2.6 on 2021-08-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20210817_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reciept',
            new_name='receipt',
        ),
    ]
