# Generated by Django 3.2.6 on 2021-08-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_rename_reciept_user_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receipt',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
