# Generated by Django 3.2.6 on 2021-08-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_user_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receipt',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to=None),
        ),
    ]
