# Generated by Django 3.2.6 on 2021-08-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_auto_20210817_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paper',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
