# Generated by Django 3.2.6 on 2021-08-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_alter_user_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='papers', verbose_name='paper'),
        ),
    ]
