# Generated by Django 3.2.5 on 2021-08-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_user_is_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worshop',
            new_name='Workshop',
        ),
    ]
