# Generated by Django 3.2.5 on 2021-08-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_rename_worshop_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workshops_subscribed',
            field=models.IntegerField(default=0),
        ),
    ]
