# Generated by Django 3.2.5 on 2021-08-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_user_workshops_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guest',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
