# Generated by Django 3.2.6 on 2021-08-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_alter_user_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribed_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_1_id', models.IntegerField(default=0, null=True)),
                ('course_2_id', models.IntegerField(default=0, null=True)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('Full_Name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
