# Generated by Django 3.2.6 on 2021-08-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_subscribed_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribed_Courses',
        ),
        migrations.AddField(
            model_name='user',
            name='course_1_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course_2_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
