# Generated by Django 3.2.6 on 2021-08-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_auto_20210827_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_1_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
