# Generated by Django 3.2.6 on 2021-08-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_user_course_2_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='guest',
            new_name='guests',
        ),
    ]
