# Generated by Django 3.2.6 on 2021-08-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_rename_guest_user_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_1_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_2_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
