# Generated by Django 3.2.6 on 2021-08-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_auto_20210828_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_1_name',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_2_name',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
    ]
