# Generated by Django 3.2.6 on 2021-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_course_taken_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_1_link',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course_2_link',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
    ]
