# Generated by Django 3.2.6 on 2021-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_auto_20210830_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
