# Generated by Django 3.2.6 on 2021-08-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_course_zoom_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_approved',
            new_name='course_1_approval',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='receipt',
            new_name='receipt_1',
        ),
        migrations.AddField(
            model_name='user',
            name='course_2_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receipt_2',
            field=models.ImageField(blank=True, null=True, upload_to='receipts', verbose_name='photo'),
        ),
    ]
