# Generated by Django 3.2.6 on 2021-08-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_auto_20210830_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course_1_approval',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course_2_approval',
        ),
    ]
