# Generated by Django 3.2.6 on 2021-08-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0042_auto_20210830_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='receipt_1',
            new_name='receipt_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receipt_2',
        ),
    ]
