# Generated by Django 3.2.6 on 2021-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_auto_20210830_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email',
            field=models.EmailField(default='course@mail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='receipts', verbose_name='Receipt Photo'),
        ),
    ]
