# Generated by Django 3.2.6 on 2021-09-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0046_auto_20210901_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefk',
            name='image',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='taken_slots',
            new_name='attendants',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cropping',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageFK',
        ),
    ]
