# Generated by Django 3.2.6 on 2021-09-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0047_auto_20210901_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_size',
            field=models.IntegerField(default=20),
        ),
    ]
