# Generated by Django 3.2.6 on 2021-09-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0049_rename_workshops_subscribed_user_courses_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='/static/image/conisoft_logo.png', upload_to=None),
        ),
    ]
