# Generated by Django 3.2.6 on 2021-09-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0051_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
