# Generated by Django 3.2.6 on 2021-09-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0053_auto_20210903_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receipt_photo',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='receipts', verbose_name='Receipt Photo'),
        ),
    ]
