# Generated by Django 3.2.6 on 2021-09-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0054_alter_user_receipt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receipt_photo',
            field=models.ImageField(default='None', null=True, upload_to='receipts', verbose_name='Receipt Photo'),
        ),
    ]
